name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
        node_options: ['']
        include:
          - node: 18
            node_options: '--openssl-legacy-provider' # node 17+ support
    env:
      STREAM_API_KEY: ${{ secrets.STREAM_API_KEY }}
      STREAM_ANALYTICS_TOKEN: ${{ secrets.STREAM_ANALYTICS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps
        env:
          NODE_OPTIONS: ${{ matrix.node_options }}
        run: yarn install

      - name: Lint ${{ matrix.node }}
        env:
          NODE_OPTIONS: ${{ matrix.node_options }}
        run: yarn run lint

      - name: Build with ${{ matrix.node }}
        env:
          NODE_OPTIONS: ${{ matrix.node_options }}
        run: yarn run build

      - name: Lint and Test with ${{ matrix.node }}
        env:
          NODE_OPTIONS: ${{ matrix.node_options }}
        run: yarn run test
